use_tab = false
font_size = 16
socket_port = 14514
socket_buffer_size = 100000

[group1]
height_of_each = 300
host = "localhost"
port = 14515
id = 1
use_gui_time = true

[group1.graph1]
name = "angle"
var1 = {name = "roll", color = [0.22, 0.77, 0.73, 0.75], width = 1.5, filled = false, buffer_size = 5000}
var2 = {name = "pitch", color = [0.5, 0.5, 0, 0.2], width = 1, filled = true}
var3 = {name = "yaw", color = [0, 1, 0, 0.5], width = 2}

# [group1.graph2]
# var4 = {color = [0, 0, 1, 0.25], width = 1}
#
# [group2]
# id = 2
# port = 14514
#
# [group2.graph1]
# 2 = {}
# 1 = {filled = true}
# foo = "baka"
# foo_var = {}
#
# [group3]
# id = 3
# [group3.graph1]
# name = "foo"
# var2 = {}
#
# [group5]
# id = 5
# [group5.graph1]
# var2 = {}
#
# [group4]
# id = 4
# [group4.graph1]
# var2 = {}

